//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Banque()
        {
            this.Compte_Bancaire = new HashSet<Compte_Bancaire>();
            this.Devise_Banque = new HashSet<Devise_Banque>();
        }
    
        public string ban_Code { get; set; }
        public string ban_Nom { get; set; }
        public string ban_Adresse { get; set; }
        public string ban_Tele { get; set; }
        public string ban_Branche { get; set; }
        public string ban_Nationalite { get; set; }
        public Nullable<System.DateTime> ban_Date_Debut { get; set; }
        public Nullable<bool> ban_Status { get; set; }
        public string ban_Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compte_Bancaire> Compte_Bancaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devise_Banque> Devise_Banque { get; set; }
    }
}
