//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bon_Destruction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bon_Destruction()
        {
            this.Bon_Destruction_Produit = new HashSet<Bon_Destruction_Produit>();
        }
    
        public string bon_D_Code { get; set; }
        public Nullable<System.DateTime> bon_D_Date { get; set; }
        public Nullable<System.TimeSpan> bon_D_Temps { get; set; }
        public string bon_D_Text { get; set; }
        public Nullable<int> bon_D_Status { get; set; }
        public string bon_D_Note { get; set; }
        public string fact_Code { get; set; }
        public string bon_T_Code { get; set; }
    
        public virtual Bon_Type Bon_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_Destruction_Produit> Bon_Destruction_Produit { get; set; }
    }
}
