//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bon_Destruction_Produit
    {
        public string prd_B_D_Code { get; set; }
        public Nullable<System.DateTime> prd_B_D_Date { get; set; }
        public Nullable<System.TimeSpan> prd_B_D_Temps { get; set; }
        public Nullable<int> prd_B_D_Quantite { get; set; }
        public string prd_B_D_Text { get; set; }
        public Nullable<int> prd_B_D_Status { get; set; }
        public string prd_B_D_Note { get; set; }
        public string prd_Code { get; set; }
        public string bon_D_Code { get; set; }
    
        public virtual Bon_Destruction Bon_Destruction { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
