//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bon_Entree_Produit
    {
        public string prd_B_E_Code { get; set; }
        public Nullable<System.DateTime> prd_B_E_Date { get; set; }
        public Nullable<System.TimeSpan> prd_B_E_Temps { get; set; }
        public Nullable<int> prd_B_E_Quantite { get; set; }
        public string prd_B_E_Text { get; set; }
        public Nullable<bool> prd_B_E_Status { get; set; }
        public string prd_B_E_Note { get; set; }
        public string prd_Code { get; set; }
        public string bon_E_Code { get; set; }
    
        public virtual Bon_Entree Bon_Entree { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
