//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bon_Sortie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bon_Sortie()
        {
            this.Bon_Sortie_Produit = new HashSet<Bon_Sortie_Produit>();
            this.Operation_Bon_Sortie_Magasin = new HashSet<Operation_Bon_Sortie_Magasin>();
        }
    
        public string bon_S_Code { get; set; }
        public Nullable<System.DateTime> bon_S_Date { get; set; }
        public Nullable<System.TimeSpan> bon_S_Temps { get; set; }
        public string bon_S_Text { get; set; }
        public Nullable<bool> bon_S_Status { get; set; }
        public string bon_S_Note { get; set; }
        public string fact_V_Code { get; set; }
        public string bon_T_Code { get; set; }
    
        public virtual Bon_Type Bon_Type { get; set; }
        public virtual Facture_Vente Facture_Vente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_Sortie_Produit> Bon_Sortie_Produit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation_Bon_Sortie_Magasin> Operation_Bon_Sortie_Magasin { get; set; }
    }
}
