//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compte_Charge
    {
        public string chrg_C_Code { get; set; }
        public string chrg_C_Nom { get; set; }
        public Nullable<System.DateTime> chrg_C_Date { get; set; }
        public Nullable<bool> chrg_C_Status { get; set; }
        public string chrg_C_Note { get; set; }
        public string chrg_Code { get; set; }
    
        public virtual Charge Charge { get; set; }
    }
}
