//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compte_Client
    {
        public string clt_C_Code { get; set; }
        public string clt_C_Nom { get; set; }
        public Nullable<System.DateTime> clt_C_Date { get; set; }
        public Nullable<decimal> clt_C_Limit_Montant { get; set; }
        public string trait_Code { get; set; }
        public Nullable<bool> clt_C_Status { get; set; }
        public string clt_C_Note { get; set; }
        public string clt_Code { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Traitement Traitement { get; set; }
    }
}
