//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compte_Local_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compte_Local_Type()
        {
            this.Compte_Local = new HashSet<Compte_Local>();
        }
    
        public string loc_C_T_Code { get; set; }
        public string loc_C_T_Nom { get; set; }
        public string loc_C_T_Type { get; set; }
        public Nullable<bool> loc_C_T_Status { get; set; }
        public string loc_C_T_Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compte_Local> Compte_Local { get; set; }
    }
}
