//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Devise()
        {
            this.Compte_Bancaire = new HashSet<Compte_Bancaire>();
            this.Devise_Banque = new HashSet<Devise_Banque>();
            this.Operation_Facture_Achat = new HashSet<Operation_Facture_Achat>();
            this.Operation_Facture_Achat_Retour = new HashSet<Operation_Facture_Achat_Retour>();
            this.Operation_Facture_Vente = new HashSet<Operation_Facture_Vente>();
            this.Operation_Facture_Vente_Retour = new HashSet<Operation_Facture_Vente_Retour>();
            this.Operation_Recu_Achat = new HashSet<Operation_Recu_Achat>();
            this.Operation_Recu_Vente = new HashSet<Operation_Recu_Vente>();
        }
    
        public string dvis_Code { get; set; }
        public string dvis_Nom { get; set; }
        public string dvis_Type { get; set; }
        public string dvis_Nationalite { get; set; }
        public Nullable<decimal> dvis_Valeur { get; set; }
        public Nullable<bool> dvis_Status { get; set; }
        public string dvis_Note { get; set; }
        public string bran_Code { get; set; }
    
        public virtual Branche Branche { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compte_Bancaire> Compte_Bancaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devise_Banque> Devise_Banque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation_Facture_Achat> Operation_Facture_Achat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation_Facture_Achat_Retour> Operation_Facture_Achat_Retour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation_Facture_Vente> Operation_Facture_Vente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation_Facture_Vente_Retour> Operation_Facture_Vente_Retour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation_Recu_Achat> Operation_Recu_Achat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation_Recu_Vente> Operation_Recu_Vente { get; set; }
    }
}
