//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devise_Banque
    {
        public string dvis_B_Code { get; set; }
        public string dvis_B_Nom { get; set; }
        public Nullable<bool> dvis_B_Status { get; set; }
        public string ban_Code { get; set; }
        public string dvis_Code { get; set; }
    
        public virtual Banque Banque { get; set; }
        public virtual Devise Devise { get; set; }
    }
}
