//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devise_Banque
    {
        public string dvis_B_Code { get; set; }
        public string dvis_B_Nom { get; set; }
        public Nullable<bool> dvis_B_Status { get; set; }
        public string ban_Code { get; set; }
        public string dvis_Code { get; set; }
    
        public virtual Banque Banque { get; set; }
        public virtual Devise Devise { get; set; }
    }
}
