//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Salaire
    {
        public string empl_S_Code { get; set; }
        public string empl_S_Nom { get; set; }
        public Nullable<decimal> empl_S_Salaire { get; set; }
        public Nullable<decimal> empl_S_Remise { get; set; }
        public Nullable<decimal> empl_S_Bonus { get; set; }
        public Nullable<decimal> empl_S_Net { get; set; }
        public Nullable<bool> empl_S_Status { get; set; }
        public string empl_S_Note { get; set; }
        public string empl_Code { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
