//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Compte_Employee = new HashSet<Compte_Employee>();
            this.Employee_Salaire = new HashSet<Employee_Salaire>();
        }
    
        public string empl_Code { get; set; }
        public string empl_Nom { get; set; }
        public string empl_Prenom { get; set; }
        public string empl_Type { get; set; }
        public Nullable<decimal> empl_Salaire { get; set; }
        public Nullable<int> empl_Heure_Travail { get; set; }
        public Nullable<System.DateTime> empl_Date_Eumbauche { get; set; }
        public string empl_Adresse { get; set; }
        public string empl_Tele { get; set; }
        public string empl_Position_Travail { get; set; }
        public Nullable<bool> empl_Status { get; set; }
        public string empl_Note { get; set; }
        public string bran_Code { get; set; }
    
        public virtual Branche Branche { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compte_Employee> Compte_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Salaire> Employee_Salaire { get; set; }
    }
}
