//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture_Achat_Bonus
    {
        public string fact_A_B_Code { get; set; }
        public Nullable<System.DateTime> fact_A_B_Date { get; set; }
        public Nullable<System.TimeSpan> fact_A_B_Temps { get; set; }
        public string fact_A_B_Text { get; set; }
        public Nullable<int> fact_A_B_Quantite { get; set; }
        public Nullable<bool> fact_A_B_Status { get; set; }
        public string fact_A_B_Note { get; set; }
        public string fact_A_Code { get; set; }
        public string prd_Code { get; set; }
        public string unt_M_Code { get; set; }
        public string unt_T_Code { get; set; }
    
        public virtual Facture_Achat Facture_Achat { get; set; }
        public virtual Produit Produit { get; set; }
        public virtual Unite_Mesure Unite_Mesure { get; set; }
        public virtual Unite_Type Unite_Type { get; set; }
    }
}
