//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture_Vente_Produit
    {
        public string fact_V_P_Code { get; set; }
        public Nullable<System.DateTime> fact_V_P_Date { get; set; }
        public Nullable<System.TimeSpan> fact_V_P_Temps { get; set; }
        public string fact_V_P_Text { get; set; }
        public Nullable<decimal> fact_V_P_Prix { get; set; }
        public Nullable<decimal> fact_V_P_Prix_Vente { get; set; }
        public Nullable<decimal> fact_V_P_Remise { get; set; }
        public Nullable<bool> fact_V_P_Remise_Type { get; set; }
        public Nullable<decimal> fact_V_P_Total { get; set; }
        public Nullable<int> fact_V_P_Quantite { get; set; }
        public Nullable<bool> fact_V_P_Status { get; set; }
        public string fact_V_P_Note { get; set; }
        public string fact_V_Code { get; set; }
        public string prd_Code { get; set; }
        public string unt_M_Code { get; set; }
        public string unt_T_Code { get; set; }
    
        public virtual Facture_Vente Facture_Vente { get; set; }
        public virtual Produit Produit { get; set; }
        public virtual Unite_Mesure Unite_Mesure { get; set; }
        public virtual Unite_Type Unite_Type { get; set; }
    }
}
