//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Impot()
        {
            this.Operation_Impot = new HashSet<Operation_Impot>();
        }
    
        public string imp_Code { get; set; }
        public Nullable<System.DateTime> imp_Date { get; set; }
        public string imp_Nom { get; set; }
        public Nullable<decimal> imp_Montant { get; set; }
        public Nullable<int> imp_Pourcentage { get; set; }
        public Nullable<bool> imp_Status { get; set; }
        public string imp_Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation_Impot> Operation_Impot { get; set; }
    }
}
