//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magasin_Branche
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magasin_Branche()
        {
            this.Produit_Emplacement = new HashSet<Produit_Emplacement>();
        }
    
        public string mgs_Branche_Code { get; set; }
        public Nullable<System.DateTime> mgs_Branche_Date { get; set; }
        public Nullable<bool> mgs_Branche_Status { get; set; }
        public string mgs_Branche_Note { get; set; }
        public string bran_Code { get; set; }
        public string mags_Code { get; set; }
    
        public virtual Branche Branche { get; set; }
        public virtual Magasin Magasin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produit_Emplacement> Produit_Emplacement { get; set; }
    }
}
