//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magasin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magasin()
        {
            this.Magasin_Branche = new HashSet<Magasin_Branche>();
        }
    
        public string mags_Code { get; set; }
        public string mags_Nom { get; set; }
        public Nullable<System.DateTime> mags_Date { get; set; }
        public string mags_Emplacement { get; set; }
        public string mags_Type { get; set; }
        public string mags_Tele { get; set; }
        public string mags_Fax { get; set; }
        public Nullable<bool> mags_Status { get; set; }
        public string mags_Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Magasin_Branche> Magasin_Branche { get; set; }
    }
}
