//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation_Bon_Sortie_Magasin
    {
        public string bon_S_Mags_Code { get; set; }
        public Nullable<System.DateTime> bon_S_Mags_Date { get; set; }
        public Nullable<System.TimeSpan> bon_S_Mags_Temps { get; set; }
        public string bon_S_Mags_Text { get; set; }
        public Nullable<bool> bon_S_Mags_Status { get; set; }
        public string bon_S_Code { get; set; }
        public string bon_T_Code { get; set; }
    
        public virtual Bon_Sortie Bon_Sortie { get; set; }
        public virtual Bon_Type Bon_Type { get; set; }
    }
}
