//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation_Recu_Achat
    {
        public string recu_A_O_Code { get; set; }
        public Nullable<System.DateTime> recu_A_O_Date { get; set; }
        public Nullable<System.TimeSpan> recu_A_O_Temps { get; set; }
        public string recu_A_O_Text { get; set; }
        public Nullable<decimal> recu_A_O_Montant { get; set; }
        public Nullable<decimal> recu_A_O_Remise { get; set; }
        public Nullable<decimal> recu_A_O_Total { get; set; }
        public Nullable<decimal> recu_A_O_Net { get; set; }
        public Nullable<bool> recu_A_O_Status { get; set; }
        public string recu_A_O_Note { get; set; }
        public string recu_A_Code { get; set; }
        public string dvis_Code { get; set; }
        public string bran_Code { get; set; }
    
        public virtual Branche Branche { get; set; }
        public virtual Devise Devise { get; set; }
        public virtual Recu_Achat Recu_Achat { get; set; }
    }
}
