//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation_Facture_Achat_Retour
    {
        public string fact_A_R_O_Code { get; set; }
        public Nullable<System.DateTime> fact_A_R_O_Date { get; set; }
        public Nullable<System.TimeSpan> fact_A_R_O_Temps { get; set; }
        public Nullable<decimal> fact_A_R_O_Montant { get; set; }
        public Nullable<decimal> fact_A_R_O_Remise { get; set; }
        public Nullable<decimal> fact_A_R_O_Total { get; set; }
        public Nullable<decimal> fact_A_R_O_Net { get; set; }
        public Nullable<bool> fact_A_R_O_Status { get; set; }
        public string fact_A_R_O_Note { get; set; }
        public string frns_Code { get; set; }
        public string dvis_Code { get; set; }
        public string fact_A_R_Code { get; set; }
        public string bran_Code { get; set; }
    
        public virtual Branche Branche { get; set; }
        public virtual Devise Devise { get; set; }
        public virtual Facture_Achat_Retour Facture_Achat_Retour { get; set; }
        public virtual Fournisseur Fournisseur { get; set; }
    }
}
