//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation_Impot
    {
        public string imp_O_Code { get; set; }
        public Nullable<System.DateTime> imp_O_Date { get; set; }
        public Nullable<System.TimeSpan> imp_O_Temps { get; set; }
        public Nullable<decimal> imp_O_Montant_tva { get; set; }
        public Nullable<decimal> imp_O_Valeur_tva { get; set; }
        public Nullable<decimal> imp_O_Net { get; set; }
        public Nullable<bool> imp_O_Status { get; set; }
        public string imp_O_Note { get; set; }
        public string imp_Code { get; set; }
    
        public virtual Impot Impot { get; set; }
    }
}
