//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation_Facture_Achat
    {
        public string fact_A_O_Code { get; set; }
        public Nullable<System.DateTime> fact_A_O_Date { get; set; }
        public Nullable<System.TimeSpan> fact_A_O_Temps { get; set; }
        public Nullable<decimal> fact_A_O_Montant { get; set; }
        public Nullable<decimal> fact_A_O_Remise { get; set; }
        public Nullable<decimal> fact_A_O_Total { get; set; }
        public Nullable<decimal> fact_A_O_Net { get; set; }
        public Nullable<bool> fact_A_O_Status { get; set; }
        public string fact_A_O_Note { get; set; }
        public string frns_Code { get; set; }
        public string dvis_Code { get; set; }
        public string fact_A_Code { get; set; }
        public string bran_Code { get; set; }
    
        public virtual Branche Branche { get; set; }
        public virtual Devise Devise { get; set; }
        public virtual Facture_Achat Facture_Achat { get; set; }
        public virtual Fournisseur Fournisseur { get; set; }
    }
}
