//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation_Caisse
    {
        public string cais_O_Code { get; set; }
        public string cais_O_Nom { get; set; }
        public Nullable<System.DateTime> cais_O_Date { get; set; }
        public Nullable<System.TimeSpan> cais_O_Temps { get; set; }
        public Nullable<decimal> cais_O_Montant { get; set; }
        public Nullable<decimal> cais_O_Total { get; set; }
        public Nullable<bool> cais_O_Type { get; set; }
        public Nullable<int> cais_O_Status { get; set; }
        public string cais_O_Note { get; set; }
        public string ban_C_Code { get; set; }
        public string esp_C_Code { get; set; }
        public string cais_Code { get; set; }
    
        public virtual Compte_Bancaire Compte_Bancaire { get; set; }
        public virtual Compte_Espece Compte_Espece { get; set; }
        public virtual Main_Caisse Main_Caisse { get; set; }
    }
}
