//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit_Emplacement
    {
        public string emp_Code { get; set; }
        public Nullable<System.DateTime> emp_Date { get; set; }
        public string emp_Place { get; set; }
        public string emp_Case { get; set; }
        public string emp_Etagere { get; set; }
        public Nullable<bool> emp_Status { get; set; }
        public string emp_Note { get; set; }
        public string prd_Code { get; set; }
        public string mgs_Branche_Code { get; set; }
    
        public virtual Magasin_Branche Magasin_Branche { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
