//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit_Detail
    {
        public string dtl_Code { get; set; }
        public string dtl_Pays_Orig { get; set; }
        public Nullable<System.DateTime> dtl_Date_Production { get; set; }
        public Nullable<System.DateTime> dtl_Date_Expiration { get; set; }
        public string dtl_Serie { get; set; }
        public string dtl_Entreprise { get; set; }
        public string dtl_Periode_Garantie { get; set; }
    
        public virtual Produit Produit { get; set; }
    }
}
