//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit_Barcode
    {
        public string brcd_Code { get; set; }
        public string brcd_Numero { get; set; }
        public string brcd_Type { get; set; }
        public Nullable<bool> brcd_Status { get; set; }
        public string brcd_Note { get; set; }
        public string prd_ID { get; set; }
    
        public virtual Produit Produit { get; set; }
    }
}
