//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit_Barcode
    {
        public string brcd_Code { get; set; }
        public string brcd_Numero { get; set; }
        public string brcd_Type { get; set; }
        public Nullable<bool> brcd_Status { get; set; }
        public string brcd_Note { get; set; }
        public string prd_ID { get; set; }
    
        public virtual Produit Produit { get; set; }
    }
}
