//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit_Image
    {
        public string img_Code { get; set; }
        public string img_Nom { get; set; }
        public string img_Emplacement { get; set; }
        public Nullable<bool> img_Status { get; set; }
        public string img_Note { get; set; }
        public string prd_Code { get; set; }
    
        public virtual Produit Produit { get; set; }
    }
}
