//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sysSalesEntities : DbContext
    {
        public sysSalesEntities()
            : base("name=sysSalesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banque> Banque { get; set; }
        public virtual DbSet<Bon_Destruction> Bon_Destruction { get; set; }
        public virtual DbSet<Bon_Destruction_Produit> Bon_Destruction_Produit { get; set; }
        public virtual DbSet<Bon_Entree> Bon_Entree { get; set; }
        public virtual DbSet<Bon_Entree_Produit> Bon_Entree_Produit { get; set; }
        public virtual DbSet<Bon_Sortie> Bon_Sortie { get; set; }
        public virtual DbSet<Bon_Sortie_Produit> Bon_Sortie_Produit { get; set; }
        public virtual DbSet<Bon_Type> Bon_Type { get; set; }
        public virtual DbSet<Branche> Branche { get; set; }
        public virtual DbSet<Charge> Charge { get; set; }
        public virtual DbSet<Charge_Type> Charge_Type { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Compte_Bancaire> Compte_Bancaire { get; set; }
        public virtual DbSet<Compte_Charge> Compte_Charge { get; set; }
        public virtual DbSet<Compte_Client> Compte_Client { get; set; }
        public virtual DbSet<Compte_Employee> Compte_Employee { get; set; }
        public virtual DbSet<Compte_Espece> Compte_Espece { get; set; }
        public virtual DbSet<Compte_Fournisseur> Compte_Fournisseur { get; set; }
        public virtual DbSet<Compte_Local> Compte_Local { get; set; }
        public virtual DbSet<Compte_Local_Type> Compte_Local_Type { get; set; }
        public virtual DbSet<Devise> Devise { get; set; }
        public virtual DbSet<Devise_Banque> Devise_Banque { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Employee_Salaire> Employee_Salaire { get; set; }
        public virtual DbSet<Entreprise_Info> Entreprise_Info { get; set; }
        public virtual DbSet<Facture_Achat> Facture_Achat { get; set; }
        public virtual DbSet<Facture_Achat_Bonus> Facture_Achat_Bonus { get; set; }
        public virtual DbSet<Facture_Achat_Produit> Facture_Achat_Produit { get; set; }
        public virtual DbSet<Facture_Achat_Produit_Retour> Facture_Achat_Produit_Retour { get; set; }
        public virtual DbSet<Facture_Achat_Retour> Facture_Achat_Retour { get; set; }
        public virtual DbSet<Facture_Paiement_Type> Facture_Paiement_Type { get; set; }
        public virtual DbSet<Facture_Type> Facture_Type { get; set; }
        public virtual DbSet<Facture_Vente> Facture_Vente { get; set; }
        public virtual DbSet<Facture_Vente_Bonus> Facture_Vente_Bonus { get; set; }
        public virtual DbSet<Facture_Vente_Produit> Facture_Vente_Produit { get; set; }
        public virtual DbSet<Facture_Vente_Produit_Retour> Facture_Vente_Produit_Retour { get; set; }
        public virtual DbSet<Facture_Vente_Retour> Facture_Vente_Retour { get; set; }
        public virtual DbSet<Fournisseur> Fournisseur { get; set; }
        public virtual DbSet<Impot> Impot { get; set; }
        public virtual DbSet<Magasin> Magasin { get; set; }
        public virtual DbSet<Magasin_Branche> Magasin_Branche { get; set; }
        public virtual DbSet<Main_Caisse> Main_Caisse { get; set; }
        public virtual DbSet<Operation_Bon_Entree_Magasin> Operation_Bon_Entree_Magasin { get; set; }
        public virtual DbSet<Operation_Bon_Sortie_Magasin> Operation_Bon_Sortie_Magasin { get; set; }
        public virtual DbSet<Operation_Caisse> Operation_Caisse { get; set; }
        public virtual DbSet<Operation_Facture_Achat> Operation_Facture_Achat { get; set; }
        public virtual DbSet<Operation_Facture_Achat_Retour> Operation_Facture_Achat_Retour { get; set; }
        public virtual DbSet<Operation_Facture_Vente> Operation_Facture_Vente { get; set; }
        public virtual DbSet<Operation_Facture_Vente_Retour> Operation_Facture_Vente_Retour { get; set; }
        public virtual DbSet<Operation_Impot> Operation_Impot { get; set; }
        public virtual DbSet<Operation_Recu_Achat> Operation_Recu_Achat { get; set; }
        public virtual DbSet<Operation_Recu_Vente> Operation_Recu_Vente { get; set; }
        public virtual DbSet<Produit> Produit { get; set; }
        public virtual DbSet<Produit_Barcode> Produit_Barcode { get; set; }
        public virtual DbSet<Produit_Boxe> Produit_Boxe { get; set; }
        public virtual DbSet<Produit_Categorie> Produit_Categorie { get; set; }
        public virtual DbSet<Produit_Detail> Produit_Detail { get; set; }
        public virtual DbSet<Produit_Emplacement> Produit_Emplacement { get; set; }
        public virtual DbSet<Produit_Image> Produit_Image { get; set; }
        public virtual DbSet<Produit_Section> Produit_Section { get; set; }
        public virtual DbSet<Produit_Type> Produit_Type { get; set; }
        public virtual DbSet<Recu_Achat> Recu_Achat { get; set; }
        public virtual DbSet<Recu_Type> Recu_Type { get; set; }
        public virtual DbSet<Recu_Vente> Recu_Vente { get; set; }
        public virtual DbSet<Traitement> Traitement { get; set; }
        public virtual DbSet<Unite_Mesure> Unite_Mesure { get; set; }
        public virtual DbSet<Unite_Type> Unite_Type { get; set; }
    
        public virtual ObjectResult<Select_Entreprise_Info_Result> Select_Entreprise_Info()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Entreprise_Info_Result>("Select_Entreprise_Info");
        }
    
        public virtual int Delete_Entreprise_Info(string entr_Code, Nullable<bool> entr_Status)
        {
            var entr_CodeParameter = entr_Code != null ?
                new ObjectParameter("entr_Code", entr_Code) :
                new ObjectParameter("entr_Code", typeof(string));
    
            var entr_StatusParameter = entr_Status.HasValue ?
                new ObjectParameter("entr_Status", entr_Status) :
                new ObjectParameter("entr_Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Entreprise_Info", entr_CodeParameter, entr_StatusParameter);
        }
    
        public virtual int Insert_Entreprise_Info(string entr_Code, string entr_Nom, string entr_Adresse, string entr_Ville, string entr_Pays, string entr_Code_Postal, string entr_Tele1, string entr_Tele2, string entr_Email, string entr_Whatsapp, string entr_Fax, Nullable<bool> entr_Status, byte[] entr_Logo, string entr_Note)
        {
            var entr_CodeParameter = entr_Code != null ?
                new ObjectParameter("entr_Code", entr_Code) :
                new ObjectParameter("entr_Code", typeof(string));
    
            var entr_NomParameter = entr_Nom != null ?
                new ObjectParameter("entr_Nom", entr_Nom) :
                new ObjectParameter("entr_Nom", typeof(string));
    
            var entr_AdresseParameter = entr_Adresse != null ?
                new ObjectParameter("entr_Adresse", entr_Adresse) :
                new ObjectParameter("entr_Adresse", typeof(string));
    
            var entr_VilleParameter = entr_Ville != null ?
                new ObjectParameter("entr_Ville", entr_Ville) :
                new ObjectParameter("entr_Ville", typeof(string));
    
            var entr_PaysParameter = entr_Pays != null ?
                new ObjectParameter("entr_Pays", entr_Pays) :
                new ObjectParameter("entr_Pays", typeof(string));
    
            var entr_Code_PostalParameter = entr_Code_Postal != null ?
                new ObjectParameter("entr_Code_Postal", entr_Code_Postal) :
                new ObjectParameter("entr_Code_Postal", typeof(string));
    
            var entr_Tele1Parameter = entr_Tele1 != null ?
                new ObjectParameter("entr_Tele1", entr_Tele1) :
                new ObjectParameter("entr_Tele1", typeof(string));
    
            var entr_Tele2Parameter = entr_Tele2 != null ?
                new ObjectParameter("entr_Tele2", entr_Tele2) :
                new ObjectParameter("entr_Tele2", typeof(string));
    
            var entr_EmailParameter = entr_Email != null ?
                new ObjectParameter("entr_Email", entr_Email) :
                new ObjectParameter("entr_Email", typeof(string));
    
            var entr_WhatsappParameter = entr_Whatsapp != null ?
                new ObjectParameter("entr_Whatsapp", entr_Whatsapp) :
                new ObjectParameter("entr_Whatsapp", typeof(string));
    
            var entr_FaxParameter = entr_Fax != null ?
                new ObjectParameter("entr_Fax", entr_Fax) :
                new ObjectParameter("entr_Fax", typeof(string));
    
            var entr_StatusParameter = entr_Status.HasValue ?
                new ObjectParameter("entr_Status", entr_Status) :
                new ObjectParameter("entr_Status", typeof(bool));
    
            var entr_LogoParameter = entr_Logo != null ?
                new ObjectParameter("entr_Logo", entr_Logo) :
                new ObjectParameter("entr_Logo", typeof(byte[]));
    
            var entr_NoteParameter = entr_Note != null ?
                new ObjectParameter("entr_Note", entr_Note) :
                new ObjectParameter("entr_Note", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Entreprise_Info", entr_CodeParameter, entr_NomParameter, entr_AdresseParameter, entr_VilleParameter, entr_PaysParameter, entr_Code_PostalParameter, entr_Tele1Parameter, entr_Tele2Parameter, entr_EmailParameter, entr_WhatsappParameter, entr_FaxParameter, entr_StatusParameter, entr_LogoParameter, entr_NoteParameter);
        }
    
        public virtual ObjectResult<Entreprise_Info> Select_Entreprise_Info_By_Name(string entr_Nom)
        {
            var entr_NomParameter = entr_Nom != null ?
                new ObjectParameter("entr_Nom", entr_Nom) :
                new ObjectParameter("entr_Nom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Entreprise_Info>("Select_Entreprise_Info_By_Name", entr_NomParameter);
        }
    
        public virtual ObjectResult<Entreprise_Info> Select_Entreprise_Info_By_Name(string entr_Nom, MergeOption mergeOption)
        {
            var entr_NomParameter = entr_Nom != null ?
                new ObjectParameter("entr_Nom", entr_Nom) :
                new ObjectParameter("entr_Nom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Entreprise_Info>("Select_Entreprise_Info_By_Name", mergeOption, entr_NomParameter);
        }
    
        public virtual int Update_Entreprise_Info(string entr_Code, string entr_Nom, string entr_Adresse, string entr_Ville, string entr_Pays, string entr_Code_Postal, string entr_Tele1, string entr_Tele2, string entr_Email, string entr_Whatsapp, string entr_Fax, Nullable<bool> entr_Status, byte[] entr_Logo, string entr_Note)
        {
            var entr_CodeParameter = entr_Code != null ?
                new ObjectParameter("entr_Code", entr_Code) :
                new ObjectParameter("entr_Code", typeof(string));
    
            var entr_NomParameter = entr_Nom != null ?
                new ObjectParameter("entr_Nom", entr_Nom) :
                new ObjectParameter("entr_Nom", typeof(string));
    
            var entr_AdresseParameter = entr_Adresse != null ?
                new ObjectParameter("entr_Adresse", entr_Adresse) :
                new ObjectParameter("entr_Adresse", typeof(string));
    
            var entr_VilleParameter = entr_Ville != null ?
                new ObjectParameter("entr_Ville", entr_Ville) :
                new ObjectParameter("entr_Ville", typeof(string));
    
            var entr_PaysParameter = entr_Pays != null ?
                new ObjectParameter("entr_Pays", entr_Pays) :
                new ObjectParameter("entr_Pays", typeof(string));
    
            var entr_Code_PostalParameter = entr_Code_Postal != null ?
                new ObjectParameter("entr_Code_Postal", entr_Code_Postal) :
                new ObjectParameter("entr_Code_Postal", typeof(string));
    
            var entr_Tele1Parameter = entr_Tele1 != null ?
                new ObjectParameter("entr_Tele1", entr_Tele1) :
                new ObjectParameter("entr_Tele1", typeof(string));
    
            var entr_Tele2Parameter = entr_Tele2 != null ?
                new ObjectParameter("entr_Tele2", entr_Tele2) :
                new ObjectParameter("entr_Tele2", typeof(string));
    
            var entr_EmailParameter = entr_Email != null ?
                new ObjectParameter("entr_Email", entr_Email) :
                new ObjectParameter("entr_Email", typeof(string));
    
            var entr_WhatsappParameter = entr_Whatsapp != null ?
                new ObjectParameter("entr_Whatsapp", entr_Whatsapp) :
                new ObjectParameter("entr_Whatsapp", typeof(string));
    
            var entr_FaxParameter = entr_Fax != null ?
                new ObjectParameter("entr_Fax", entr_Fax) :
                new ObjectParameter("entr_Fax", typeof(string));
    
            var entr_StatusParameter = entr_Status.HasValue ?
                new ObjectParameter("entr_Status", entr_Status) :
                new ObjectParameter("entr_Status", typeof(bool));
    
            var entr_LogoParameter = entr_Logo != null ?
                new ObjectParameter("entr_Logo", entr_Logo) :
                new ObjectParameter("entr_Logo", typeof(byte[]));
    
            var entr_NoteParameter = entr_Note != null ?
                new ObjectParameter("entr_Note", entr_Note) :
                new ObjectParameter("entr_Note", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Entreprise_Info", entr_CodeParameter, entr_NomParameter, entr_AdresseParameter, entr_VilleParameter, entr_PaysParameter, entr_Code_PostalParameter, entr_Tele1Parameter, entr_Tele2Parameter, entr_EmailParameter, entr_WhatsappParameter, entr_FaxParameter, entr_StatusParameter, entr_LogoParameter, entr_NoteParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Entreprise_Info()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Entreprise_Info");
        }
    }
}
